name: iOS Minimal Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install npm dependencies
      run: npm install --legacy-peer-deps

    - name: Modify Podfile to disable Flipper
      run: |
        cd ios
        # 备份原Podfile
        cp Podfile Podfile.backup

        # 创建最小化的Podfile
        cat > Podfile << 'EOF'
        # Explicitly specify the project
        project 'ABCBankApp.xcodeproj'

        require Pod::Executable.execute_command('node', ['-p',
          'require.resolve(
            "react-native/scripts/react_native_pods.rb",
            {paths: [process.argv[1]]},
          )', __dir__]).strip

        platform :ios, min_ios_version_supported
        prepare_react_native_project!

        # 禁用Flipper
        flipper_config = FlipperConfiguration.disabled

        target 'HelloWorld' do
          config = use_native_modules!
          flags = get_default_flags()

          use_react_native!(
            :path => config[:reactNativePath],
            :hermes_enabled => flags[:hermes_enabled],
            :fabric_enabled => flags[:fabric_enabled],
            :flipper_configuration => flipper_config,
            :app_path => "#{Pod::Config.instance.installation_root}/.."
          )

          target 'HelloWorldTests' do
            inherit! :complete
          end

          post_install do |installer|
            react_native_post_install(
              installer,
              config[:reactNativePath],
              :mac_catalyst_enabled => false
            )
          end
        end
        EOF

    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --verbose

    - name: Build iOS App
      run: |
        cd ios
        xcodebuild -workspace ABCBankApp.xcworkspace \
                   -scheme HelloWorld \
                   -configuration Release \
                   -destination 'platform=iOS Simulator,name=iPhone 14' \
                   -derivedDataPath ./build \
                   build

    - name: Package and Upload
      run: |
        cd ios/build/Build/Products/Release-iphonesimulator/
        if [ -d "HelloWorld.app" ]; then
          zip -r HelloWorld-iOS-App.zip HelloWorld.app
          echo "✅ 应用打包成功!"
          ls -la HelloWorld-iOS-App.zip
        else
          echo "❌ 未找到.app文件"
          ls -la
        fi

    - name: Upload iOS App
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: iOS-App-Minimal-${{ github.run_number }}
        path: ios/build/Build/Products/Release-iphonesimulator/HelloWorld-iOS-App.zip
        retention-days: 30